### ISSUE TITLE
Register more than 2 images simultaneously?

### ISSUE THREAD

**Issue by ajr82** [NHPatterson/wsireg#49]
* wsireg version: 0.3.0
* Python version: 3.10
* Operating System: Win 10

Hi, this is a very nice tool! 

Is is possible to register more than 2 images simultaneously? I was trying out 3 images and ended up with an error.

----> 1 reg_graph.add_reg_path(
      2     "modality_brightfield",
      3     "modality_brightfield2",
      4     "modality_brightfield3",
      5     thru_modality=None,
      6     reg_params=["rigid", "affine"],
      7 )

TypeError: add_reg_path() got multiple values for argument 'thru_modality'

Thank you.

**Comment by NHPatterson** [comment]
Hi @ajr82 Thanks for trying things out and I'm happy to help you get going. First off, you may want to update `wsireg` to v0.3.2.2. There have been some improvements to the library since v0.3.0.

You can upgrade like this:
```bash
pip install --upgrade wsireg
```

To your question...

Yes you can absolutely do this and this is one of the most important features of `wsireg`! You've just made a small error in the set-up. Registration paths (`.add_reg_path()`) have to be set up individually. Below I give 2 examples on how to do this depending on your circumstances. They also show how to incorporate non-rigid transformations (desirable if you are using data coming from serial sections) in `reg_params` argument and indirect registrations through the graph. 

## simple example with multiple tissue sections all aligning to `mod_bf2`
```python
# register with bf1 to bf2 with rigid and affine transforms
reg_graph.add_reg_path("mod_bf1","mod_bf2", reg_params = ["rigid","affine"])

# register bf3 to bf2 using rigid, affine, and non-rigid deformation (nl)
reg_graph.add_reg_path("mod_bf3","mod_bf2", reg_params=["rigid","affine","nl"])
```

Depending on your use case you can also set up a chain of registrations where `bf1` is aligned to `bf2` and `bf3` is aligned to `bf1` then uses the transforms from the `bf1` to `bf2` to go to `bf2`.

## concatenating transformations in the graph (indirect registration)
```python
# register with bf1 to bf2 with rigid and affine transforms
reg_graph.add_reg_path("mod_bf1","mod_bf2", reg_params = ["rigid","affine"])

# register bf3 to bf2 indirectly by registered 
# we add "mod_bf1" to the "thru_modality" argument
# this registers bf3 to bf1 but then uses the transformation from bf1 to bf2
# this is useful when bf2 is more similar to bf1 and bf3 is most similar to bf1
reg_graph.add_reg_path("mod_bf3","mod_bf2",  thru_modality="mod_bf1", reg_params = ["rigid","affine"])
```

I am releasing the napari GUI for this library soon with a long instructional video that should help clarify, but for the time-being see below on how to do this. It's simple enough.
